# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Alex Lohse
tagline:          'GTech MSE'
description:      'GaTech PhD Student in MSE'
url:              
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5
disqus:           alohse

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/alohse
